### ISSUE TITLE
Auto-reacts for promotions

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#129]
Line 45 doesn't seem to trigger right. Intended behavior is for it to add auto react like with Scirra stuff.
![image](https://user-images.githubusercontent.com/15656049/75188640-c4da6700-574c-11ea-91c6-721ccc3d25c7.png)
Code:
https://github.com/WebCreationClub/alfred-botler/blob/master/commands/everyone/promo.js

**Comment by TheRealDannyyy** [comment]
Could perhaps be fixed by using:
`await addReactions(sent, 'notification');`

**Comment by Armaldio** [comment]
What reactions should be added ?

**Comment by TheRealDannyyy** [comment]
Same as in the screenshot. Up and New.

**Comment by TheRealDannyyy** [comment]
Wait cut that, just the upvote arrow is enough.
