### ISSUE TITLE
Broken "!Promo" removal using capital letter

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#143]
1. Use `!Promo` instead of the expected `!promo`
2. Notice "!Promo" not being removed as expected
![image](https://user-images.githubusercontent.com/15656049/79975441-49bad600-849b-11ea-8534-fc66a6289bff.png)

**Comment by TheRealDannyyy** [comment]
Not fixed.

**Comment by Armaldio** [comment]
Should be fixed now
