### ISSUE TITLE
Error using move command

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#144]
Check logs for:
![image](https://user-images.githubusercontent.com/15656049/79975563-77a01a80-849b-11ea-9d69-1485e7f7d8a3.png)

**Comment by Armaldio** [comment]
Logs too far away
Better to have reproduction steps

**Comment by TheRealDannyyy** [comment]
No clue, didn't happen to me. Try to catch it next time.
