### ISSUE TITLE
Add new "!ask" command

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#147]
`!ask` content draft:
- manual links
- bug command
- context (e.g. details; screenshots; short video; example project)
- debugging helper

**Comment by Armaldio** [comment]
Added the command, you can update the template

**Comment by TheRealDannyyy** [comment]
Can you change it so it posts directly instead of a private message?

**Comment by TheRealDannyyy** [comment]
Reminding myself to update git readme with new command later.

**Comment by Armaldio** [comment]
Done
