### ISSUE TITLE
Make !temptest relative to available templates

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#148]
It's currently limited to a selected amount of templates. Ideally it should automatically check for what's available to test and also suggest them in error cases.

![image](https://user-images.githubusercontent.com/15656049/80547631-025fa880-89b9-11ea-8bcf-53a692a58cd6.png)

**Comment by Armaldio** [comment]
Changed
Will only load these:
![image](https://user-images.githubusercontent.com/3089715/80636805-4ce73080-8a5e-11ea-9c9a-6c135bfbb922.png)

Is that right ?

**Comment by TheRealDannyyy** [comment]
I'm planning to add a new template just for testing things in the future. So basically everything in the templates folder.

**Comment by Armaldio** [comment]
I mean that I'm not including subfolders

**Comment by TheRealDannyyy** [comment]
All good then.
