### ISSUE TITLE
Discord API Domain Migration

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#153]
_Last month, we excitedly announced our official move to discord.com. It was a long time in the making, and the work isn't done yet! For now, our API will continue to handle requests made to discordapp.com. On November 7, 2020 we will be dropping support for the discordapp.com domain in favor of discord.com. Please ensure that your libraries, bots, and applications are updated accordingly._

_Due to technical constraints, our CDN domain will not be migrated and will remain cdn.discordapp.com for the foreseeable future._

**Comment by pedrofracassi** [comment]
If you're on the latest version of discord.js, you should be fine. They've updated the domains on their source code already.

**Comment by Armaldio** [comment]
Yeah 👍
