### ISSUE TITLE
Fix or Remove GitHub 3rd Party Imgbot

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#155]
That bot has been inactive or not working correctly for a while. Let's fix it or remove it, including the branch.
https://github.com/WebCreationClub/alfred-botler/tree/imgbot

**Comment by Armaldio** [comment]
There you go: https://github.com/WebCreationClub/alfred-botler/pull/156

**Comment by TheRealDannyyy** [comment]
Thx.
