### ISSUE TITLE
Undefined channel on error

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#163]
![image](https://user-images.githubusercontent.com/15656049/93094223-eb88cc80-f6a1-11ea-8882-33d33fc610c4.png)

**Comment by Armaldio** [comment]
Next time, add a link to the message 👍

**Comment by TheRealDannyyy** [comment]
https://canary.discordapp.com/channels/116497549237551109/116497549237551109/754859081285763212
