### ISSUE TITLE
Job Offers - Full Automation

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#28]
- Offer posting form
- Offer type templates
- Offer deletion

**Comment by TheRealDannyyy** [comment]
@Armaldio Want to get this off the ground or is the existing job offers channel good enough?
We could do something like the Prebuilds website with a separate repo and ad monetization.

**Comment by TheRealDannyyy** [comment]
Reworked channel structure suggestion:
- Simple headline + forum link structure (+optional media upload)
- Check for hyperlink/text requirement: forum/game-development/job-offers-and-team-requests & www.construct.net
[Code: DO Check text; ERROR Remove message + post 20sec. error message + post PM with copy of removed text]
- Disable message editing (prevents bypassing link/text requirement. edits can be done by deleting and reposting)
- Disable link embeds to prevent double embedding (e.g. if media is attached)

**Comment by Armaldio** [comment]
------ post error message with 20sec auto-deletion timeout (e.g. "Sorry your post requires #ERRORHERE#!")
------ post PM with copy of removed message

Why not make a single message ?

**Comment by TheRealDannyyy** [comment]
20sec. auto-deletion timeout would make it hard to copy it in time. PM would be permanent.

**Comment by Armaldio** [comment]
I mean all in DM

**Comment by Armaldio** [comment]
Good point

**Comment by TheRealDannyyy** [comment]
You can do it PM only if you like. 
At the core of it, there just needs to be a way to tell the user that something went wrong.

**Comment by Armaldio** [comment]
I think we can close this
Won't happen soon
