### ISSUE TITLE
Move Community Blog Posts To Promotion Channel

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#55]
Might as well, since we got this channel now. (Is changing [this](https://github.com/WebCreationClub/alfred-botler/blob/master/bot-utils.js#L142) constant variable enough?)

**Comment by Armaldio** [comment]
Why would we do that ?

**Comment by TheRealDannyyy** [comment]
Keeping the community channel clean.

**Comment by Armaldio** [comment]
So then what's the use of the community channel?

Le lun. 25 mars 2019 à 14:11, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
The same as it has always been. Server and game jam announcements.

**Comment by Armaldio** [comment]
Go on then

**Comment by Armaldio** [comment]
Replace the constant with the right other constant

**Comment by TheRealDannyyy** [comment]
What's the right constant? There are two for promotion.

**Comment by Armaldio** [comment]
CONSTANTS.CHANNELS.PROMO
