### ISSUE TITLE
Command - warn

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#6]
New Warning Proposal:
1. Submit to moderation log using form
2. Warn user with command "!warn ###username###"

**Comment by TheRealDannyyy** [comment]
I'd simplify this command entirely.

Make one unified template which states that the user has been warned for breaking one or more rules. If the user in questions why the warning happened, give reason found inside https://docs.google.com/spreadsheets/d/1RhCDfUMQnZs-QFAY3hV5XLJEipBDa3Wu3Vq4kvViW1c/edit#gid=0.

New warning propsal:
1. Add user + reason to spreadsheet
2. Warn user with command (!warn @userhere)
3. Give reason if requested, based on spreadsheet

**Comment by Armaldio** [comment]
The form do the whole job ? Can we close this ?

**Comment by TheRealDannyyy** [comment]
No the user still has to know it, else there is no way to know, if a warning has been received.

**Comment by TheRealDannyyy** [comment]
Further simplified the command with notice to contact support, instead of using another command. 

The legacy moderation log has been ported over to the new automated one. This means that existing punishments remain but follow the new process.

**Comment by Armaldio** [comment]
I need clarification.
Do the warn command should take a punishment and a reason ?

'Cause the template make no mention for that

**Comment by TheRealDannyyy** [comment]
No it's like that on purpose. 

Reason will be logged only, from now on. If the individual asks for it, anyone available can just look it up and give the reason.

**Comment by TheRealDannyyy** [comment]
The individual will notice a mute or ban. Again if asked why, we can provide a reason based on the logs.

If you really think that it's required, I could do templates for each punishment. I think it's just additional work.

**Comment by Armaldio** [comment]
So if the punishment is not a warn, the user don't get a notification ?

Not needed, just asking questions for now

**Comment by TheRealDannyyy** [comment]
I don't see a reason for it since they will know based on, not being able to post things.

You don't really have that kind of "active" punishment when being warned.

**Comment by Armaldio** [comment]
ok
