### ISSUE TITLE
Broken embeds for duplicated messages

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#60]
Embeds inside the promotion channel sometimes don't work. 
Needs to be investigated at some point to find the cause.

_Issue example:_
![Issue](https://user-images.githubusercontent.com/15656049/55728029-95771a80-5a13-11e9-8084-3d1f0beec4e8.PNG)

_Expected result:_
![Expected](https://user-images.githubusercontent.com/15656049/55727998-88f2c200-5a13-11e9-882a-81757a3474b4.PNG)

**Comment by Armaldio** [comment]
I think it's a Discord issue

**Comment by TheRealDannyyy** [comment]
Possible workaround could be to detect if an embed exists, if not repeat the duplication.

**Comment by TheRealDannyyy** [comment]
Latest canary has minor updates to embeds. This might be fixed now.
