### ISSUE TITLE
Announcement subversion bug (regression)

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#61]
![image](https://user-images.githubusercontent.com/15656049/57077687-f4674100-6cec-11e9-8d61-598eeea612fb.png)
(This also breaks the releases list.)

**Comment by Armaldio** [comment]
Scirra seems to have forgotten the link themself (it's as is on their website)
The link works

**Comment by TheRealDannyyy** [comment]
https://github.com/Scirra/Construct.net-website-bugs/issues/95

The releases list can be edited manually, so let's fix that one on our end.

**Comment by Armaldio** [comment]
I'm following the report, once fixed i'll edit the link in the database

**Comment by TheRealDannyyy** [comment]
@Armaldio Can you for the time being put it in the right order?
(Between r147 beta and r148 stable, with correct empty spaces.)
