### ISSUE TITLE
Server Consent + Extra Features

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#69]
- [x] Announce new rules and nickname availability
- [x] Give everyone the _member_ role (use bot to automatically add role to new users)
- [x] Allow "change nickname" access for _member_ role
- [x] Disable "change nickname" access for _everyone_ role
- [x] Give "manage nickname" and "change nickname" access to staff

**Comment by TheRealDannyyy** [comment]
Another option could be to automatically give everyone the "Member" role and add a command to revoke consent (!denyconsent). This would also require to give everyone no access to chatting + uploading as a default.

**Comment by TheRealDannyyy** [comment]
Turns out consent isn't required unless your server has NSFW or deemed "naughty" by Discord. So just giving everyone on the server the member role should be good enough.

**Comment by Armaldio** [comment]
So, we do this or, give @everyone nickname edit and use the 'No Nick' role ?

**Comment by TheRealDannyyy** [comment]
You cannot deny permissions given to everyone.

**Comment by Armaldio** [comment]
Ah, so No Nick can override Member ?

**Comment by TheRealDannyyy** [comment]
Yes.

**Comment by Armaldio** [comment]
I'm about to give everyone the Member role
Is that right ?

**Comment by TheRealDannyyy** [comment]
Yes. We also need the bot to automatically give new users the member role.

**Comment by Armaldio** [comment]
I think it's done

**Comment by TheRealDannyyy** [comment]
Announcement is gonna happen soon.
