### ISSUE TITLE
Switch to MEE6 Bot

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#70]
- [x] Disable + kick Pingcord from CC
- [x] Invite MEE6 bot to CC
- [x] Override/disable any settings except YT and Twitch notifications

ref: https://mee6.xyz/

**Comment by TheRealDannyyy** [comment]
@Armaldio I can't invite Mee6 because it requires admin permissions. Please invite and manage it yourself or temporally give me admin perms.

**Comment by Armaldio** [comment]
I've invited mee6 and enabled moderation, youtube and twitch

**Comment by TheRealDannyyy** [comment]
No need for any features except yt + twitch, we got botler for that.

**Comment by Armaldio** [comment]
Disabled moderator features then
Le 10/07/2019 à 10:15, TheRealDannyyy a écrit :

**Comment by TheRealDannyyy** [comment]
Also make sure to disable leveling and all that other stuff. I'll disable and kick pingcord later.
