### ISSUE TITLE
easier construct version control

### ISSUE THREAD

**Issue by erenertugrul** [WebCreationClub/alfred-botler#71]
Hi, @Armaldio and @TheRealDannyyy 
 I'm developing a discord bot.
I had a look to alfred-botle codes as an example. it looks very nice.
anyway I found these links.

c3 releases
https://www.construct.net/sitemap_productrelease_1.xml

c2 releases
https://www.scirra.com/construct2/version.txt

maybe you might want to use it for the "checkC3Updates" and  "checkC2Updates" functions.

you can look for other links here. 
https://www.construct.net/robots.txt

**Comment by erenertugrul** [comment]
ohh i just noticed.
you receive the content of the site. I'm just getting the new version.
so this suggestion may not work for you. :)

![yy](https://user-images.githubusercontent.com/27224622/62409454-410a3300-b5e0-11e9-9df3-d2117419906b.png)

**Comment by Armaldio** [comment]
Yeah, by fetching the website directly, we get additional infos

Le sam. 3 août 2019 à 10:17, Eren Ertuğrul <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Armaldio's code, didn't do much on this end.

**Comment by TheRealDannyyy** [comment]
Closing since the existing system seems to be better.
