### ISSUE TITLE
Line overlap in embeds

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#72]
![image](https://user-images.githubusercontent.com/15656049/62412615-90168f00-b605-11e9-8826-b4d4e9e00b71.png)

**Comment by Armaldio** [comment]
What size of screen ?

**Comment by TheRealDannyyy** [comment]
Ask the creator of the previous bug. Can't reproduce.

**Comment by Armaldio** [comment]
@erenertugrul

**Comment by TheRealDannyyy** [comment]
Either way this can be fixed by only using 20 line chars or trying to use an image of a line instead (if possible).

**Comment by erenertugrul** [comment]
@Armaldio 1920x1080

![aa](https://user-images.githubusercontent.com/27224622/62413406-551d5700-b617-11e9-9fbe-7db0cebeba21.png)

**Comment by Armaldio** [comment]
Ok, but the window obviously isn't full-width
Will fix that with a smaller line
Not sure we can add an image inline

**Comment by TheRealDannyyy** [comment]
I think it's caused by the OS rendering the line char differently and not the size.

Try 20 chars instead of what we have now.

**Comment by erenertugrul** [comment]
@TheRealDannyyy  yes the problem is caused by the mac os default text font.

**windows**
![windows](https://user-images.githubusercontent.com/27224622/62413808-0f16c200-b61c-11e9-95e4-f14886f7c20f.png)

**macos**

![mac](https://user-images.githubusercontent.com/27224622/62413812-19d15700-b61c-11e9-8294-75e3976c0a01.png)

**Comment by TheRealDannyyy** [comment]
@erenertugrul How many chars is the overflow on your mac? Let's use that number and do -5 to be safe.

**Comment by erenertugrul** [comment]
I compared three different samples.

"29-5" and "28-6"

![gonder](https://user-images.githubusercontent.com/27224622/62414729-396e7c80-b628-11e9-807a-8ed5193fca58.png)

**Comment by TheRealDannyyy** [comment]
Thanks. Let's remove 8 line chars and call it a day.
