### ISSUE TITLE
Role list command dynamic values

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#73]
Updating [the spreadsheet](https://docs.google.com/spreadsheets/d/1KDcw40KowYoJTjohKaUyzEFvmCoXAXPmd4tEqZwU170/edit#gid=0) is annoying and nobody does it anyway.
Let's create a simple command that displays all available roles in a list.

Changes:
- [x] Create role list template
- [x] Create role list command
- [x] Remove role table spreadsheet
- [x] Replace role info text in existing templates (howto, added, removed)
- [x] Update Git readme
- [x] Update message with dynamic values (https://github.com/WebCreationClub/alfred-botler/blob/bba23e940c209cb202fa9358017dbc57ac65ad70/templates/Announcement_RoleInfo.js)

Example:
![image](https://user-images.githubusercontent.com/15656049/62798745-55b66180-badf-11e9-8ebb-330dab4a2176.png)

**Comment by Armaldio** [comment]
> Remove "!iam" cancel process and display role list instead
The cancel proces is automatic by the lib I use

**Comment by TheRealDannyyy** [comment]
Richembed is possible but not required so closing.
