### ISSUE TITLE
Bug and Rolelist don't remove initial command

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#78]
I won't touch this since a mistake could wipe the entire channel clean.

**Comment by Armaldio** [comment]
You can use deleteCmd: true, in the class constructor like in https://github.com/WebCreationClub/alfred-botler/blob/master/commands/moderation/move.js

**Comment by TheRealDannyyy** [comment]
Doesn't seem to work. Please look into it when you can.
