### ISSUE TITLE
Update report command with channel name + add reference link

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#81]
Seems like we have to go back to the old system. With the addition of the bot-commands channel, people use commands from there and that results in wrong context for reports.

Easiest way for including the right context is a channel requirement in the command itself.

**Command:**
- Example: !report #general

**PM:**
- Error case 1 (no channel): Please include the channel name for context.
- Error case 2 (wrong param): Channel doesn't exist! Please make sure it's written correctly and try again.

<hr>

Put message reference link into manual review log message.

**Example:**
https://canary.discordapp.com/channels/116497549237551109/244447929400688650/614088411405484052

**Comment by TheRealDannyyy** [comment]
Merge #84

**Comment by Armaldio** [comment]
report command now include a link to the message

- !report -> link to the report message
- !report #messageId -> link to the message with the specific id

**Comment by TheRealDannyyy** [comment]
I'm not so sure if this is a good idea. We want to keep things simple to use.

I will check it out tomorrow.

**Comment by TheRealDannyyy** [comment]
I don't know about this, I have the feeling nobody is gonna use the ID method. 
This might be a more straight forward system:
1. Use !report (remove command)
2. Private question asking for Message ID or Channel Name
3. Show context preview (always show 10 recent messages)
4. Confirm report or cancel

**Comment by Armaldio** [comment]
That's tedious
If is is not usefull, I'll stay with the very basic `!report`

**Comment by TheRealDannyyy** [comment]
Then just do the report command but use a channel reference as mentioned before.
!report #channelname#

**Comment by Armaldio** [comment]
I still think it's weird to report something in another channel from where
it's happening

Le mer. 28 août 2019 à 16:07, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Yet it happened. There is a stigma with submitting reports, that's why some users prefer to report it outside of the current channel or in similar anonymous ways.

Your decision in the end. I think not considering the thing mentioned above was an oversight, when we introduced the simplified report command.

**Comment by TheRealDannyyy** [comment]
Closed for now. Optional enhancement that could be re-opened in the future.
