### ISSUE TITLE
Report command bugs

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#82]
- Fix:  (<@&[object Object]>)

**Comment by TheRealDannyyy** [comment]
Workaround using everyone tag. Nobody else has except staff can access the channel anyway.

**Comment by Armaldio** [comment]
You should have done CONSTANTS.ROLES.STAFF.id

Le jeu. 22 août 2019 à 15:54, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Changed back to start again, thanks for info.
