### ISSUE TITLE
Wrong user tag on error

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#86]
![image](https://user-images.githubusercontent.com/15656049/63651293-6f98ab00-c753-11e9-997e-0f7145354ec1.png)
([at]armaldio not tagged right.)

**Comment by skymen** [comment]
I can't find that message in Alfred's source code. What command caused this?

**Comment by TheRealDannyyy** [comment]
1. Server privacy settings to block PMs from server
2. For testing: `!move 0 #bin`
3. Wait 5sec for error popup

**Comment by Armaldio** [comment]
Fixed by bc8e1da49c09a5decea8e2a1a016ade12c062312

On error, a message is sent to #moderators describing the issue (see https://discordapp.com/channels/116497549237551109/227786972020604929/682335529496346735)
